repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.46.0  # Note: this is the version of the pre-commit hook, NOT the pyrefly version used for type checking
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: false  # Recommended to do full repo checks. However, you can change this to `true` to only check changed files
  # - repo: local
  #   hooks:
  #     - id: ty
  #       name: ty check
  #       entry: uv run ty check . --ignore unresolved-import
  #       language: python
